# -*- coding: utf-8 -*-
"""DataLabel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvfIGh-cXucv0ENtTNweE3sX4zuOri-p
"""

import pandas as pd
import google.generativeai as genai
import os
import time

Data = pd.read_csv("DataText.csv")

Data.head()

SelectedData = Data[0:200]

Emotion = []

value = os.getenv("APIKEY")

genai.configure(api_key="APIKEY")

model = genai.GenerativeModel('gemini-pro')

for i in range(0,200):
    try:
        Text = SelectedData["description"][i] + """ \n Is this a positive or negative or neutral statement? Just give one word"""
        print(Text)
        response = model.generate_content(Text)
        print(response.text)
        Emotion.append(response.text)
    except ValueError:
        Emotion.append("Undecided")
        print(i)
    time.sleep(120)

len(Emotion)

with open("EmotionLabels.csv","a") as file:
    for i in Emotion[101:]:
        l = i +","+ "\n"
        file.write(l)

for i, j in enumerate(Emotion):
    if j == "Undecided":
        print(i)
        print(SelectedData["description"][i])
        print("\n")

DataLabeled = pd.read_csv('EmotionLabels.csv')

DataLabeled

SelectedData["SentimentalLabels"] = DataLabeled["Labels"]

SelectedData.to_csv("SentimentalLabels.csv")

